// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUMwvE3ekavVWyEzBju8uFSvnM_tdDmb0',
    appId: '1:588577749625:web:1a012048476b5ca164f2a8',
    messagingSenderId: '588577749625',
    projectId: 'shoppingo-118d6',
    authDomain: 'shoppingo-118d6.firebaseapp.com',
    storageBucket: 'shoppingo-118d6.appspot.com',
    measurementId: 'G-WVNYZYPGLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuIkcNFgczYg_-JTAS9GdZ_RWFNtbrYIk',
    appId: '1:588577749625:android:941645ac8712f10964f2a8',
    messagingSenderId: '588577749625',
    projectId: 'shoppingo-118d6',
    storageBucket: 'shoppingo-118d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFwjvQ0XC_iIiW6ESXrAFrOz5m4uorZNQ',
    appId: '1:588577749625:ios:35609977e1bab99164f2a8',
    messagingSenderId: '588577749625',
    projectId: 'shoppingo-118d6',
    storageBucket: 'shoppingo-118d6.appspot.com',
    iosBundleId: 'com.example.demo1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFwjvQ0XC_iIiW6ESXrAFrOz5m4uorZNQ',
    appId: '1:588577749625:ios:81aa4f12f087a0b464f2a8',
    messagingSenderId: '588577749625',
    projectId: 'shoppingo-118d6',
    storageBucket: 'shoppingo-118d6.appspot.com',
    iosBundleId: 'com.example.demo1.RunnerTests',
  );
}
